#!/bin/bash

if [ ! -d plugins ]; then
    echo "Script must be run on root folder" >&2
    exit 1
fi

if [[ -z $1 ]]; then
    echo "Missing argument 1: plugin-name"
    echo "Usage: plugin-git plugin-name action"
    exit 2
fi

if [[ -z $2 ]]; then
    echo "Missing argument 2: action"
    echo "Usage: plugin-git plugin-name action"
    exit 2
fi

if [[ $1 == "all" ]]; then
    baseDir=$(pwd)
    for D in $(find plugins/mce/ -maxdepth 1 -mindepth 1 -type d); do
        echo $(tput bold)"Checking $D..."$(tput sgr0)
        cd $(realpath $D)
        if [[ $2 == "status" ]]; then
            git status
            cd $baseDir
        elif [[ $2 == "push" ]] && [[ -z $3 ]]; then
            git add .
            git commit -m "$3"
            git push
            cd $baseDir
        fi
    done
fi


